FROM openjdk:11
copy ./target/OnlineMedicineShoppingSystem-0.0.1-SNAPSHOT.jar OnlineMedicineShoppingSystem-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar","OnlineMedicineShoppingSystem-0.0.1-SNAPSHOT.jar"]

