---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicialshopping-deployment
  labels:
       app: myapp
spec:
  replicas: 1
  template:
    metadata:
      name: medicalshopping-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: onlinemedicineshoppingsystem
          image: vinay265/onlinemedicineshoppingsystem
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
  selector:
    matchLabels:
      app: myapp

---
apiVersion: v1
kind: Service
metadata:
  name: medicalsystem-service
spec:
  type : NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: myapp

